### ISSUE TITLE
Language Section need to flexible width

### ISSUE THREAD

**Issue by cracki** [noparvar/resumecraft#2]
I think it is better to make the language items width dynamic
[ width: 25%](https://github.com/noparvar/resumecraft/blob/89e8ec2cc4f8abbec082ad230d33d1582813a144/resources/templates/languages.twig#L5)

**Comment by noparvar** [comment]
You are absolutely right. The problem is that I didn't find any combination of HTML and CSS to be supported in mPDF to do that. Maybe I didn't search well. But I'll fix it somehow ;)

**Comment by noparvar** [comment]
It is fixed know
